### ISSUE TITLE
[Suggestion] Ajouter un onglet "Capture d'écran" sur le site web

### ISSUE THREAD

**Issue by DegrangeM** [ClementGre/PDF4Teachers-Website#1]
Personnellement quand je vois parler d'un logiciel, j'aime pouvoir voir à quoi il ressemble avant de le télécharger.

Pour l'instant on peut trouver une capture d'écran en passant soit par la doc, soit par le lien github mais ce n'est pas pratique.

Ce serait surement plus "vendeur" d'avoir clairement un endroit où voir à quoi ressemble le logiciel.

**Comment by ClementGre** [comment]
Je pense que ce serait en faire trop que de créer une page dédié aux captures d'écran.
Mais il est vrais qu'il serait bien d'ajouter des captures d'écran sur le site WEB, dans les pages Accueil et À Propos.

J'ai aussi comme projet de créer un trailer (une vidéo) présentant les atouts de l'application.

\- Clément Grennerat

**Comment by ClementGre** [comment]
Une manière d'afficher des captures d'écran de l'application a été trouvée : les captures d'écrans sortent de la droite et sont renouvelées automatiquement sur la page d'accueil.
